### ISSUE TITLE
Error running docker-compose on windows 10 w-o hyperv running docker-toolbox on virtualbox 

### ISSUE THREAD

**Issue by mlisanke** [jbelmont/api-workshop#8]
(base) D:\workspace\api-workshop>make dev
docker-compose up mongo redis apid web
[31mERROR[0m: In file '.\docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
make: *** [Makefile:10: dev] Error 1

(base) D:\workspace\api-workshop>cat docker-compose.yml
version: '3'
services:
  mongo:
    image: mongo:3.4.5
    command: --storageEngine wiredTiger --smallfiles

**Comment by jbelmont** [comment]
@mlisanke try to update your docker-compose version if you can: https://github.com/docker/compose/issues/3331 I believe it is because of the version of docker-compose that you are using.

Here is my version information for docker and docker-compose:

<img width="511" alt="screen shot 2019-01-27 at 9 52 00 am" src="https://user-images.githubusercontent.com/2974744/51802547-37f76e00-2219-11e9-94cb-9745afbb1208.png">
